### ISSUE TITLE
Game doesn't recongize mod

### ISSUE THREAD

**Issue by lubcubsgaming** [Kardane/UsefulCommand#1]
Not sure if I am missing a dependency of some sort, but when I add the mod to the game. It just doesn't load it. Looking at console it doesn't show it loading the mod. Looking in the mod menu it does not show up and in game none of the custom commands work. Using version 1.1 on fabric loader 0.14.19

**Comment by Kardane** [comment]
I noticed that problem in certain enviroment as well!
I will upload newer version when I back home.
Thanks!

**Comment by Kardane** [comment]
Fixed!
